name: Renovate

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  renovate:
    name: Renovate
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
